### ISSUE TITLE
struct-id syntax class usage errors on some fields

### ISSUE THREAD

**Issue by adjkant** [lexi-lambda/syntax-classes#2]
Hi!

I'm currently trying to use this package in another library and ran into issues with non-syntax values being returned for attributes on the `struct-id` syntax class. I made some modifications in my own version but wasn't able to fully recreate all intended functionality without errors or issues, so I thought this may be better as an issue than a PR. You can find my modified version here, which can certainly be cleaned up / improved upon:

https://github.com/adjkant/json-sourcery/blob/fe293fb27d1fac49ff5936a229e139f7e6bb845c/json-sourcery/struct-id.rkt

Here's a code snippet of breaking code that would work with the modified version:

```
#lang racket

(require (for-syntax racket/base
                     syntax/parse
                     syntax/parse/class/struct-id))

(require syntax/parse/define)

(define-syntax foo
  (syntax-parser
    [(_ id:struct-id)
     (displayln #'id.all-fields-visible?)
     (displayln #'id.supertype-id)
     (displayln #'id.num-fields)
     (displayln #'id.num-supertype-fields)
     (displayln #'id.num-own-fields)
     #'"see prints above"]))

(struct bar [a b c])
(foo bar)
```

Happy to elaborate or help as needed!

Thanks for the work on the package, it saved me a lot of time :)

**Comment by lexi-lambda** [comment]
The non-syntax valued attributes are intentional. You can access the values of the attributes using the `attribute` form, so you can write `(attribute id.all-fields-visible?)` to get back a boolean, instead of getting a syntax-wrapped boolean.

**Comment by adjkant** [comment]
Ah I was not aware of that form, thank you!
