### ISSUE TITLE
Version exception for Racket 6.10.1

### ISSUE THREAD

**Issue by SuzanneSoy** [lexi-lambda/syntax-classes#3]
Hi!

`syntax-classes` as well as the `-lib`, `-doc` and `-test` packages have a version exception on https://pkgs.racket-lang.org for Racket 6.10 and 6.11, but there is no version exception for Racket 6.10.1.

Installation of `syntax-classes-lib` fails on Racket 6.10.1 because the latest version depends on base 6.12.

Could you add a version exception for Racket 6.10.1 for these packages ?

Thanks!

**Comment by lexi-lambda** [comment]
Fixed.

**Comment by SuzanneSoy** [comment]
Thanks! :)
