### ISSUE TITLE
Racket doesn't understand urls for version exceptions 6.1.1 and earlier

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/syntax-classes#4]
The version exceptions for versions 6.0 through 6.1.1 currently have the url:
```
https://github.com/lexi-lambda/syntax-classes.git?path=syntax-classes-lib#version-exception--6.2
```
Which is a format that Racket 6.1.1 doesn't understand. They should be changed to this instead:
```
git://github.com/lexi-lambda/syntax-classes?path=syntax-classes-lib#version-exception--6.2
```
To use `git://` instead of `https://` so that the versions of Racket those exceptions are made for can understand them

**Comment by lexi-lambda** [comment]
Fixed.
